spring:
  application:
    name: api25


  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: api
    password: apipass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

